
# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

# Flyway
spring.flyway.enabled=false

# Google
spring.security.oauth2.client.registration.google.client-id=dummy_client_id
spring.security.oauth2.client.registration.google.client-secret=dummy_secret

#Quartz
spring.quartz.auto-startup=false
spring.quartz.job-store-type=jdbc