-- Migration: Create watched movie history table
-- Version: 10
-- Description: Initial schema creation for watched movie history table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS watched_movie_history (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    movie_id bigint not null,
    updated_at timestamp(6),
    user_id bigint not null,
    watched_at timestamp(6) not null,
    primary key (id)
);

-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.watched_movie_history IS 'Stores watched movie history information';