-- Migration: Create user role table
-- Version: 1
-- Description: Initial schema creation for user roles table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS roles(
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.roles IS 'Stores user roles information';