-- Migration: Create users table
-- Version: 3
-- Description: Initial schema creation for users table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS users (
    enabled boolean not null,
    created_at timestamp(6) not null,
    google_token_expiry timestamp(6) with time zone,
    id bigint generated by default as identity,
    role_id bigint not null,
    updated_at timestamp(6),
    google_access_token varchar(500),
    google_refresh_token varchar(500),
    email varchar(255) not null unique,
    password varchar(255),
    provider varchar(255) check ((provider in ('LOCAL','GOOGLE'))),
    provider_id varchar(255),
    username varchar(255) not null unique,
    primary key (id)
);

-- Create index on email for faster lookups
CREATE INDEX idx_users_email ON users(email);

-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.users IS 'Stores user account information';