-- Migration: Create confirmation token table
-- Version: 4
-- Description: Initial schema creation for confirmation token table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS confirmation_token (
    revoked boolean not null,
    confirmed_at timestamp(6),
    created_at timestamp(6),
    expires_at timestamp(6) not null,
    id bigint generated by default as identity,
    user_id bigint, token_hash varchar(255) not null,
    primary key (id)
);


-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.confirmation_token IS 'Stores information about confirmation token';