-- Migration: Create password reset token table
-- Version: 5
-- Description: Initial schema creation for password reset token table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS password_reset_token (
    revoked boolean not null,
    confirmed_at timestamp(6),
    created_at timestamp(6),
    expires_at timestamp(6),
    id bigint generated by default as identity,
    user_id bigint,
    token_hash varchar(255) not null,
    primary key (id)
);


-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.password_reset_token IS 'Stores password reset token information';