-- Migration: Create movies table
-- Version: 1
-- Description: Initial schema creation for movies table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS movies (
    after_credits boolean,
    during_credits boolean,
    rating numeric(38,2),
    release_date date,
    runtime integer,
    us_digital_date date,
    us_physical_date date,
    us_theatrical_date date,
    created_at timestamp(6),
    id bigint generated by default as identity,
    tmdb_id bigint unique,
    trakt_id bigint unique,
    updated_at timestamp(6),
    votes bigint, us_certification varchar(20),
    backdrop varchar(255),
    certification varchar(255),
    imdb_id varchar(255) unique,
    original_title varchar(255),
    overview TEXT, poster varchar(255),
    tagline varchar(255),
    title varchar(255) not null,
    trailer varchar(255),
    tmdb_genres json,
    primary key (id)
);


-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.movies IS 'Stores movies information';