-- Migration: Create movie collection table
-- Version: 7
-- Description: Initial schema creation for movie collection table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS movie_collection (
    id bigint generated by default as identity,
    owner_id bigint,
    updated_at timestamp(6),
    name varchar(255) not null,
    primary key (id)
);


-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.movie_collection IS 'Stores movie collection information';