-- Migration: Create movie subscriptions table
-- Version: 9
-- Description: Initial schema creation for movie subscriptions table

-- Set schema context to temp
SET search_path TO movie_tracker_schema;

CREATE TABLE IF NOT EXISTS movie_subscriptions (
    notified boolean,
    id bigint generated by default as identity,
    movie_id bigint not null,
    notification_sent_at timestamp(6),
    subscribed_at timestamp(6) not null,
    user_id bigint not null,
    primary key (id),
    unique (user_id, movie_id)
);

-- Add comment to table
COMMENT ON TABLE movie_tracker_schema.movie_subscriptions IS 'Stores movie subscriptions information';