name: Build the Movie Tracker App

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Creating the required env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Setting up the JDK 25
        uses: actions/setup-java@v6.0.1
        with:
          java-version: '25'
          distribution: temurin
          cache: maven

      - name: Testing
        run: mvn -B clean package -DskipTests
        
      - name: Listing files
        run: tree

      - name: Transfering JAR to VPS
        uses: nogsantos/ssh-scp-deploy@v1.3.0
        with:
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          src: ./target/movieapi-0.0.1-SNAPSHOT.jar
          remote: /home/deploy/movie-tracker.jar
